echo 'version: "1"

services:
  - type: web
    name: proyecto_unewed
    runtime: python
    repo: https://github.com/JACKBLACKCCS/proyecto_unewed
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: marketplace
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: 3.11
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
    region: oregon
    buildCommand: |
      pip install -r requirements.txt
      cd marketplace
      python manage.py collectstatic --noinput --clear
      python manage.py migrate
    startCommand: cd marketplace && gunicorn marketplace.wsgi:application

  - type: web
    name: pgadmin-unewed
    runtime: docker
    plan: free
    dockerfilePath: Dockerfile.pgadmin
    envVars:
      - key: PGADMIN_DEFAULT_EMAIL
        value: admin@unewed.com
      - key: PGADMIN_DEFAULT_PASSWORD
        generateValue: true
    region: oregon' > render.yaml