version: "1"

services:
  - type: web
    name: proyecto_unewed
    runtime: python
    repo: https://github.com/JACKBLACKCCS/proyecto_unewed
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: marketplace
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: 3.11
    
    region: oregon
      buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn marketplace.wsgi:application