version: "1"
services:

  - type: web
    name: proyecto_unewed
    runtime: python
    repo: https://github.com/JACKBLACKCCS/proyecto_unewed
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: marketplace
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11
      - key: SECRET_KEY
        generateValue: true
    region: oregon
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py migrate
    releaseCommand: |
      python manage.py createsuperuser --noinput || true
    startCommand: gunicorn marketplace.wsgi:application

  - type: web
    name: pgadmin-unewed
    runtime: docker
    plan: free
    dockerfilePath: Dockerfile.pgadmin
    envVars:
      - key: PGADMIN_DEFAULT_EMAIL
        value: admin@unewed.com
      - key: PGADMIN_DEFAULT_PASSWORD
        generateValue: true
    region: oregon
